### ISSUE TITLE
Crash on iOS Simulator 9.x on Query.Run() execution

### ISSUE THREAD

**Issue by SeeD-Seifer** [couchbase/couchbase-lite-net#894]
Using **Couchbase Lite 2.0.0-b0195** and executing `query.Run()` on non-empty DB the app crashes on Simulator 9.x with exception (**Important: It works on Simulator 10.3!**):
```
dyld: Symbol not found: _sqlite3_value_subtype
  Referenced from: /<path-to-sim>/MyApp.iOS.app/libLiteCore.dylib
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib
```

Log before exception:
```
Couchbase Lite 2.0.0-b0195 (feature/api-v2: 23f1d6d)
Opening database at /<path-to-sim>/Library/Application Support/CouchbaseLite/accounts.cblite2
Opening DataFile
Query encoded as {"WHERE":["=",[".type"],"account"]}
Compiled Query: SELECT sequence, key, version, flags FROM kv_default WHERE fl_value(body, 'type') = 'account' LIMIT $limit OFFSET $offset
dyld: lazy symbol binding failed: Symbol not found: _sqlite3_value_subtype
  Referenced from: /<path-to-sim>/MyApp.iOS.app/libLiteCore.dylib
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib
```

Repository code:
```csharp
	public class AccountRepository: IAccountRepository
	{
		readonly Database database;
		readonly Lazy<IQuery> queryAll;

		public AccountRepository ()
		{
			database = new Database ("accounts");
			queryAll = new Lazy<IQuery> (ConstructQueryAll, isThreadSafe: false);
		}

		public IList<Account> GetAll ()
		{
			return queryAll.Value.Run ()
				           .Select (row => DocumentToAccount (row.Document))
				           .ToList ();
		}

		public void Put (Account account)
		{
			var doc = database.GetDocument (account.UUID) ?? new Document (account.UUID);
			doc.Set ("name", account.Name);
			doc.Set ("type", "account");
			database.Save (doc);
		}

		IQuery ConstructQueryAll ()
		{
			return Query.Select ()
				        .From (DataSource.Database (database))
				        .Where (Expression.Property ("type").EqualTo ("account"));
		}

		Account DocumentToAccount (Document doc)
		{
			return new Account
			{
				UUID = doc.Id,
				Name = doc.GetString ("name"),
			};
		}
	}
```

`GetAll()` called on app start. It doesn't crash on the first launched. The crash happens only when at least one account added and the app restarted.

**Comment by borrrden** [comment]
This is a known issue at the moment.  iOS 9 ships with an older version of SQLite that doesn't have all the functionality we need.  We will be addressing this in the future by compiling in the SQLite symbols statically that we need (more accurately, sqlcipher so that we can support encryption).

**Comment by borrrden** [comment]
Alright things are set up to statically link SQLite now, so in DB015 this issue will be gone.
